version: "3.3"
services:
  portainer:
    ports:
      #- '8022:8000'
      #- '8021:9443'
      - "9010:9000"
    container_name: portainer
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/aaron/serving/portainer/data:/data"
    image: "portainer/portainer-ce"
    security_opt:
      - apparmor:unconfined
    # TRAEFIK
    networks:
      - reverseproxynetwork
    labels:
      - "traefik.http.routers.portainer.rule=Host(`portainerlocal.ceim.cl`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.entrypoints=https"
      - "traefik.http.routers.portainer.middlewares=authentik@file"
  portainer_agent:
    ports:
      - 9001:9001
    container_name: portainer_agent
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    image: "portainer/agent"
    security_opt:
      - apparmor:unconfined
networks:
  reverseproxynetwork:
    name: reverseproxynetwork
    driver: bridge
  # reverseproxynetwork:
  # external: true