---
- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/gits"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"


- name: Clone or update dotfiles_stow Git repository into gits folder
  ansible.builtin.git:
    repo: 'https://github.com/JaKooLit/Debian-Hyprland.git'
    dest: "{{ ansible_env.HOME }}/gits/Debian-Hyprland"
    version: main
    update: yes
  become_user: "{{ ansible_user }}"

...