---
- name: Install gui packages
  package:
    name:
      - firefox-esr
      - kitty
      - keepassxc
      - pcmanfm
      - jstest-gtk
      - qbittorrent
      - dmenu
      - chromium
    state: present
...