---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: yes

- name: Install stow
  apt:
    name: stow
    state: present

- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/gits
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Check if stowed file exists
  ansible.builtin.find:
    paths: /home/{{ ansible_user }}/.config
    patterns: "stowed_desktop"
    file_type: any
  register: stowed_desktop

- name: clenup, execute stow uninstall desktop
  become_user: "{{ ansible_user }}"
  shell:
    cmd: /home/{{ ansible_user }}/gits/dotfiles_stow/stow_uninstall_desktop.sh
  when: stowed_desktop.matched == true
  changed_when: false

- name: Clone or update dotfiles_stow Git repository into gits folder
  ansible.builtin.git:
    repo: 'https://github.com/aaroncruces/dotfiles_stow.git'
    dest: /home/{{ ansible_user }}/gits/dotfiles_stow
    version: master
    update: yes
  become: no

- name: install, execute stow install desktop
  become_user: "{{ ansible_user }}"
  shell:
    cmd: /home/{{ ansible_user }}/gits/dotfiles_stow/stow_install_desktop.sh
  changed_when: false
...