---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: yes

- name: Install stow
  apt:
    name: stow
    state: present

- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/gits"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if stowed file exists
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.config"
    patterns: "stowed_desktop"
    file_type: any
  register: stowed_desktop

- name: clenup, execute stow uninstall desktop
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_uninstall_desktop.sh"
  when: stowed_desktop.matched == true
  changed_when: false

- name: Clone or update dotfiles_stow Git repository into gits folder
  ansible.builtin.git:
    repo: 'https://github.com/aaroncruces/dotfiles_stow.git'
    dest: "{{ ansible_env.HOME }}/gits/dotfiles_stow"
    version: master
    update: yes
  become_user: "{{ ansible_user }}"


- name: install, execute stow install desktop
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_install_desktop.sh"
  changed_when: false
  become_user: "{{ ansible_user }}"
...