- name: Template {{ template_tf }}.tf.j2 to {{ hostname }}.tf
  ansible.builtin.template:
    src: "{{ template_tf }}.tf.j2"
    dest: "{{ playbook_dir }}/terraform_run/{{ hostname }}.tf"
    mode: '0644'
  delegate_to: localhost

- name: Run Terraform for {{ hostname }}
  cloud.terraform.terraform:
    project_path: "{{ playbook_dir }}/terraform_run"
    state: present
    force_init: true
    provider_upgrade: true
    lock: true
    targets:
      - proxmox_virtual_environment_container.{{ hostname }}
  delegate_to: localhost
  register: tf_output

- name: Run install ansible with Terraform for {{ hostname }}
  cloud.terraform.terraform:
    project_path: "{{ playbook_dir }}/terraform_run"
    state: present
    force_init: true
    provider_upgrade: true
    lock: true
    targets:
      - null_resource.install_ansible_{{ hostname }}
  delegate_to: localhost
  register: tf_output

- name: Display Terraform output for Docker LXC
  ansible.builtin.debug:
    msg: "{{ tf_output }}"
  delegate_to: localhost  # Added this to run locally

