- name: Create terraform_run directory if it doesn't exist
  ansible.builtin.file:
    path: "{{ playbook_dir }}/terraform_run"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Template main.tf.j2 to main.tf
  ansible.builtin.template:
    src: main.tf.j2
    dest: "{{ playbook_dir }}/terraform_run/main.tf"
    mode: '0644'
  delegate_to: localhost
