---
all:
  hosts:
    remote:
      ansible_host: 192.168.1.111
      ansible_port: 111
      ansible_user: user
      ansible_become: true
      ansible_become_password: pass
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3.11
      ansible_ssh_passphrase: ""