---
- name: Create user and add to systemd groups
  user:
    name: "{{ ansible_new_user }}"
    groups: adm,systemd-journal
    append: yes
    create_home: true
    shell: /bin/bash
    state: present

- name: Ensure groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ group_list.split(',') }}"
  vars:
    group_list: "tty,video,kvm,input,disk,audio,cdrom,floppy,sudo,dip,plugdev,users,netdev,docker"
    
- name: Add user common groups
  user:
    name: "{{ ansible_new_user }}"
    groups: tty,video,kvm,input,disk,audio,cdrom,floppy,sudo,dip,plugdev,users,netdev,docker
    append: yes

- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: "/home/{{ ansible_new_user }}/gits"
    state: directory
    mode: '0755'
    owner: "{{ ansible_new_user }}"
    group: "{{ ansible_new_user }}"
    
- name: Allow ansible user to run poweroff and reboot without password
  become: true
  lineinfile:
    path: /etc/sudoers.d/{{ ansible_new_user }}
    line: "{{ ansible_new_user }} ALL=(root) NOPASSWD: /sbin/poweroff, /sbin/reboot"
    create: yes
    state: present
    mode: '0440'
    owner: root
    group: root
    validate: '/usr/sbin/visudo -cf %s'
...