---
- name: Install required packages
  package:
    name:
      - fontconfig
    state: present

- name: Check if JetBrains fonts are already installed
  find:
    paths: "{{ ansible_env.HOME }}/.local/share/fonts"
    patterns: "JetBrains*"
  register: jetbrains_fonts

- name: Create fonts directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: jetbrains_fonts.matched == 0

- name: Download JetBrainsMono font
  get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.tar.xz
    dest: "{{ ansible_env.HOME }}/gits/JetBrainsMono.tar.xz"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: jetbrains_fonts.matched == 0

- name: Extract JetBrainsMono font
  unarchive:
    src: "{{ ansible_env.HOME }}/gits/JetBrainsMono.tar.xz"
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: jetbrains_fonts.matched == 0

- name: Remove Windows fonts
  ansible.builtin.command:
    cmd: rm -rvf "{{ ansible_env.HOME }}/.local/share/fonts/*Windows*"
  ignore_errors: true
  when: jetbrains_fonts.matched == 0

- name: Update font cache
  command:
    cmd: fc-cache -fv
  ignore_errors: true
  when: jetbrains_fonts.matched == 0
  become_user: "{{ ansible_user }}"
