---
- name: Check if nvim exists
  command: which nvim
  register: nvim_check
  ignore_errors: true
  changed_when: false

- name: Install required packages for Docker
  apt:
    name:
      - build-essential
      - cmake
      - lua5.4
    state: present
  when: nvim_check.rc != 0
  
- name: Clone neovim repository
  git:
    repo: https://github.com/neovim/neovim.git
    dest: /home/{{ ansible_user }}/gits/neovim
    version: stable
    update: yes
  become_user: "{{ ansible_user }}"
  when: nvim_check.rc != 0

- name: Build neovim
  shell:
    cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
    chdir: /home/{{ ansible_user }}/gits/neovim
  become_user: "{{ ansible_user }}"
  when: nvim_check.rc != 0

- name: Install neovim
  shell:
    cmd: sudo make install
    chdir: /home/{{ ansible_user }}/gits/neovim
  become: true
  when: nvim_check.rc != 0 