---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: yes

- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/gits
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Clone or update dotfiles_stow Git repository into gits folder
  ansible.builtin.git:
    repo: 'https://github.com/aaroncruces/dotfiles_stow.git'
    dest: /home/{{ ansible_user }}/gits/dotfiles_stow
    version: master
    update: yes
  become: no

- name: Install stow
  apt:
    name: stow
    state: present

- name: check if /home/{{ ansible_user }}/gits/dotfiles_stow/ exists  
  stat:
    path: /home/{{ ansible_user }}/gits/dotfiles_stow/
  register: dotfiles_stow_exists
  changed_when: false

- name: Check if stowed file exists
  find:
    paths: /home/{{ ansible_user }}/.config
    patterns: "stowed"
  register: stowed

- name: clenup, execute stow uninstall common
  become_user: "{{ ansible_user }}"
  shell:
    cmd: /home/{{ ansible_user }}/gits/dotfiles_stow/stow_uninstall_common.sh
  when: stowed.matched == 1 and dotfiles_stow_exists.stat.exists == true
  changed_when: false

- name: install, execute stow install common
  become_user: "{{ ansible_user }}"
  shell:
    cmd: /home/{{ ansible_user }}/gits/dotfiles_stow/stow_install_common.sh
  changed_when: false
...