---
- name: Add user to systemd groups
  user:
    name: "{{ ansible_user }}"
    groups: adm,systemd-journal
    append: yes

- name: Add user common groups
  user:
    name: "{{ ansible_user }}"
    groups: tty,video,kvm,input,disk,audio,cdrom,floppy,sudo,dip,plugdev,users,netdev,gamemode
    append: yes

- name: Ensure gits folder exists for the current user
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/gits
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: no

- name: Allow ansible user to run poweroff and reboot without password
  become: true
  lineinfile:
    path: /etc/sudoers.d/{{ ansible_user }}
    line: "{{ ansible_user }} ALL=(root) NOPASSWD: /sbin/poweroff, /sbin/reboot"
    create: yes
    state: present
    mode: '0440'
    owner: root
    group: root
    validate: '/usr/sbin/visudo -cf %s'
...