---
- name: Check if docker exists
  command: which docker
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Install required packages for Docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  when: docker_check.rc != 0
  become: true

- name: Create apt keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: docker_check.rc != 0
  become: true

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  when: docker_check.rc != 0
  become: true

- name: Add Docker repository
  apt_repository:
    repo: deb [arch={{ ansible_architecture | regex_replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker
  when: docker_check.rc != 0
  become: true

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: docker_check.rc != 0
  become: true

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: docker_check.rc != 0 
  become: true

- name: Ensure dockers folder exists for the current user
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/dockers"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"