---
- name: Deploy GRUB configuration
  template:
    src: grub.j2
    dest: /etc/default/grub
    owner: root
    group: root
    mode: '0644'
  register: grub_config

- name: Update GRUB configuration
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub_config.changed 