---
- name: ---> check if /opt/retropie/configs/all exists
  stat:
    path: /opt/retropie/configs/all
  register: opt_all_exists
  become_user: "{{ ansible_user }}"
  changed_when: false

- name: check if "{{ ansible_env.HOME }}/RetroPie exists"
  stat:
    path: "{{ ansible_env.HOME }}/RetroPie"
  register: retropie_exists
  changed_when: false

- name: link /opt/retropie/configs/all/ to "{{ ansible_env.HOME }}/RetroPie"
  file:
    src: /opt/retropie/configs/all/
    dest: "{{ ansible_env.HOME }}/RetroPie/config_all"
    state: link
  when: opt_all_exists.stat.exists == true and retropie_exists.stat.exists == true
