---
- name: Install RetroPie dependencies
  apt:
    name:
      - git
      - dialog
      - unzip
      - xmlstarlet
    state: present

- name: Check if RetroPie-Setup exists
  stat:
    path: "{{ ansible_env.HOME }}/gits/RetroPie-Setup"
  register: retropie_check

- name: Clone RetroPie-Setup repository
  git:
    repo: https://github.com/RetroPie/RetroPie-Setup.git
    dest: "{{ ansible_env.HOME }}/gits/RetroPie-Setup"
    depth: 1
  when: not retropie_check.stat.exists 