---
- name: Install stow
  apt:
    name: stow
    state: present

- name: check if "{{ ansible_env.HOME }}/gits/dotfiles_stow/ exists  "
  stat:
    path: "{{ ansible_env.HOME }}/gits/dotfiles_stow/"
  register: dotfiles_stow_exists
  changed_when: false

- name: Check if stowed_redtower file exists
  find:
    paths: "{{ ansible_env.HOME }}/.config"
    patterns: "stowed_redtower"
  register: stowed_redtower

- name: execute stow uninstall redtower
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_uninstall_redtower.sh"
  when: stowed_redtower.matched == 1 and dotfiles_stow_exists.stat.exists == true
