---
- name: check if "{{ ansible_env.HOME }}/gits exists  "
  stat:
    path: "{{ ansible_env.HOME }}/gits"
  register: gits_exists
  changed_when: false

- name: create gits directory
  become_user: "{{ ansible_user }}"
  file:
    path: "{{ ansible_env.HOME }}/gits"
    state: directory
  when: gits_exists.stat.exists == false

- name: update dotfiles_stow repository
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ vault_dotfiles_stow_repo_https }}"
    dest: "{{ ansible_env.HOME }}/gits/dotfiles_stow"
    version: "{{ vault_dotfiles_stow_branch }}"
    update: yes

- name: execute stow install common
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_install_common.sh"
  
- name: execute stow install redtower
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_install_redtower.sh"

- name: execute stow install retropie
  become_user: "{{ ansible_user }}"
  shell:
    cmd: "{{ ansible_env.HOME }}/gits/dotfiles_stow/stow_install_retropie.sh"
